name: Sync LeetCode Solutions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Sync Solutions
        run: python .github/scripts/sync_leetcode.py
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}

      - name: Commit
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add .

          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "[LeetCode] Auto Sync"
            git push
          fi
